// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA86qw3ijek7wUVVPv4pr9obPOWE77VPXI',
    appId: '1:164452331074:web:1028afd5fff082cb9907db',
    messagingSenderId: '164452331074',
    projectId: 'psl-app-98e9a',
    authDomain: 'psl-app-98e9a.firebaseapp.com',
    storageBucket: 'psl-app-98e9a.firebasestorage.app',
    measurementId: 'G-SB7GR7G3GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwKmxCI-arwYff8UJ80f5SPBCqI_VoHcE',
    appId: '1:164452331074:android:8489dd953a3bb4099907db',
    messagingSenderId: '164452331074',
    projectId: 'psl-app-98e9a',
    storageBucket: 'psl-app-98e9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzfCiKYVtcRPQ1etaM2swGyjm6nAbz0-k',
    appId: '1:164452331074:ios:1ee73c22b944c15d9907db',
    messagingSenderId: '164452331074',
    projectId: 'psl-app-98e9a',
    storageBucket: 'psl-app-98e9a.firebasestorage.app',
    iosBundleId: 'com.example.pslApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzfCiKYVtcRPQ1etaM2swGyjm6nAbz0-k',
    appId: '1:164452331074:ios:1ee73c22b944c15d9907db',
    messagingSenderId: '164452331074',
    projectId: 'psl-app-98e9a',
    storageBucket: 'psl-app-98e9a.firebasestorage.app',
    iosBundleId: 'com.example.pslApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA86qw3ijek7wUVVPv4pr9obPOWE77VPXI',
    appId: '1:164452331074:web:8ea001f88502c9fc9907db',
    messagingSenderId: '164452331074',
    projectId: 'psl-app-98e9a',
    authDomain: 'psl-app-98e9a.firebaseapp.com',
    storageBucket: 'psl-app-98e9a.firebasestorage.app',
    measurementId: 'G-PHKYFXFGY7',
  );
}
